spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9091/~/.scavenger/db;MODE=MySQL;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: scavenger
    password: scavenger
    driver-class-name: org.h2.Driver

scavenger:
  collector-server-url: http://localhost:8080
